# Generated by Django 4.0 on 2022-06-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_activationcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activationcode',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone_number_activated',
            field=models.BooleanField(default=False),
        ),
    ]
